<tt>
&lt;div&nbsp;dir=&quot;ltr&quot;&gt;I&nbsp;noticed&nbsp;that AlreadyClosedException&nbsp;always&nbsp;sets hardError&nbsp;and&nbsp;initiatedByApplication&nbsp;to&nbsp;true,&nbsp;even&nbsp;if&nbsp;the&nbsp;error&nbsp;was&nbsp;not&nbsp;hard&nbsp;(only&nbsp;the&nbsp;channel&nbsp;was&nbsp;closed)&nbsp;and&nbsp;the&nbsp;channel&nbsp;was&nbsp;not&nbsp;closed&nbsp;by&nbsp;the&nbsp;application.&nbsp;This&nbsp;makes&nbsp;it&nbsp;more&nbsp;difficult&nbsp;to&nbsp;properly&nbsp;recover&nbsp;a&nbsp;closed&nbsp;resource&nbsp;if&nbsp;I&nbsp;can&amp;#39;t&nbsp;easily&nbsp;determine&nbsp;which&nbsp;resource&nbsp;was&nbsp;closed&nbsp;and&nbsp;why.&nbsp;Could&nbsp;this&nbsp;be&nbsp;fixed?&lt;div&gt;<br>
&lt;br&gt;&lt;/div&gt;&lt;div&gt;Cheers,&lt;/div&gt;&lt;div&gt;Jonathan&lt;/div&gt;&lt;/div&gt;<br>

</tt>
