<tt>
I&nbsp;am&nbsp;running&nbsp;some&nbsp;tests&nbsp;for&nbsp;an&nbsp;async&nbsp;process&nbsp;that&nbsp;consumes&nbsp;messages&nbsp;from&nbsp;rabbitmq.&nbsp;We&nbsp;are&nbsp;trying&nbsp;to&nbsp;figure&nbsp;out&nbsp;how&nbsp;to&nbsp;gracefully&nbsp;handle&nbsp;rabbitmq&nbsp;going&nbsp;away&nbsp;and&nbsp;coming&nbsp;back.&nbsp;The&nbsp;goal&nbsp;is&nbsp;to&nbsp;have&nbsp;the&nbsp;async&nbsp;process&nbsp;reconnect&nbsp;and&nbsp;resume&nbsp;operations.&nbsp;To&nbsp;simulate&nbsp;the&nbsp;situation&nbsp;I&nbsp;start&nbsp;my&nbsp;consumer,&nbsp;then&nbsp;I&nbsp;turn&nbsp;rabbitmq&nbsp;off,&nbsp;wait&nbsp;then&nbsp;turn&nbsp;it&nbsp;back&nbsp;on.&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;As&nbsp;expected,&nbsp;Connection&nbsp;Refused&nbsp;exceptions&nbsp;are&nbsp;thrown&nbsp;(and&nbsp;caught)&nbsp;while&nbsp;rabbitmq&nbsp;is&nbsp;off.&nbsp;As&nbsp;soon&nbsp;as&nbsp;I&nbsp;bring&nbsp;the&nbsp;server&nbsp;back&nbsp;online,&nbsp;it&nbsp;throws&nbsp;ShutDownSignalExceptions:&lt;/div&gt;&lt;div&gt;<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
&lt;p&nbsp;class=&quot;p1&quot;&gt;&lt;span&nbsp;class=&quot;s1&quot;&gt;com.rabbitmq.client.ShutdownSignalException&lt;/span&gt;:&nbsp;connection&nbsp;error;&nbsp;reason:&nbsp;{#method&amp;lt;connection.close&amp;gt;(reply-code=320,&nbsp;reply-text=CONNECTION_FORCED&nbsp;-&nbsp;broker&nbsp;forced&nbsp;connection&nbsp;closure&nbsp;with&nbsp;reason&nbsp;'shutdown',&nbsp;class-id=0,&nbsp;method-id=0),&nbsp;null,&nbsp;&quot;[B@275e538e&quot;}&lt;br&gt;at&amp;nbsp;com.rabbitmq.client.QueueingConsumer.handle(&lt;span&nbsp;class=&quot;s1&quot;&gt;QueueingConsumer.java:198&lt;/span&gt;)&lt;br&gt;at&nbsp;com.rabbitmq.client.QueueingConsumer.nextDelivery(&lt;span&nbsp;class=&quot;s1&quot;&gt;QueueingConsumer.java:214&lt;/span&gt;)&lt;br&gt;&lt;br&gt;&lt;/p&gt;&lt;p&nbsp;class=&quot;p1&quot;&gt;How&nbsp;do&nbsp;I&nbsp;gracefully&nbsp;handle&nbsp;the&nbsp;shutdown&nbsp;so&nbsp;that&nbsp;I&nbsp;can&nbsp;get&nbsp;back&nbsp;to&nbsp;consuming?&nbsp;I&nbsp;attempted&nbsp;shutting&nbsp;the&nbsp;channel&nbsp;/&nbsp;connection&nbsp;and&nbsp;creating&nbsp;a&nbsp;new&nbsp;connection&nbsp;from&nbsp;the&nbsp;factory&nbsp;but&nbsp;the&nbsp;shutdown&nbsp;signal&nbsp;exception&nbsp;is&nbsp;still&nbsp;thrown&nbsp;after&nbsp;'reconnect'.&nbsp;What's&nbsp;going&nbsp;on&nbsp;under&nbsp;the&nbsp;hood&nbsp;that&nbsp;keeps&nbsp;me&nbsp;from&nbsp;successfully&nbsp;consuming&nbsp;again?&nbsp;Is&nbsp;there&nbsp;some&nbsp;sort&nbsp;of&nbsp;message&nbsp;I&nbsp;need&nbsp;to&nbsp;tell&nbsp;RabbitMQ&nbsp;&quot;yes&nbsp;I&nbsp;know&nbsp;I&nbsp;shut&nbsp;you&nbsp;down,&nbsp;but&nbsp;its&nbsp;you're&nbsp;back&nbsp;up&nbsp;so&nbsp;stop&amp;nbsp;crying...&quot;&lt;/p&gt;&lt;p&nbsp;class=&quot;p1&quot;&gt;Thanks,&lt;/p&gt;&lt;p&nbsp;class=&quot;p1&quot;&gt;Matt&lt;/p&gt;&lt;/div&gt;
</tt>
