<tt>
&lt;div&nbsp;dir=&quot;ltr&quot;&gt;&lt;div&gt;&lt;div&gt;Hi&nbsp;all,&nbsp;&lt;br&gt;&lt;br&gt;&lt;/div&gt;I&#39;m&nbsp;getting&nbsp;INTERNAL_ERROR&nbsp;when&nbsp;I&#39;m&nbsp;running&nbsp;Rabbitmq-management-exchange&nbsp;simple_test&nbsp;from&nbsp;my&nbsp;freshly&nbsp;cloned&nbsp;rabbitmq-public-umbrella&nbsp;repo.&lt;br&gt;&lt;/div&gt;I&nbsp;don&#39;t&nbsp;see&nbsp;anything&nbsp;inside&nbsp;test&nbsp;log&nbsp;file.&lt;br&gt;<br>
&lt;div&gt;&lt;div&gt;&lt;br&gt;The&nbsp;simple_test&nbsp;outup&nbsp;is&nbsp;:&lt;br&gt;&lt;br&gt;rabbit_exchange_type_management_test:&nbsp;simple_test&nbsp;(module&nbsp;&#39;rabbit_exchange_type_management_test&#39;)...*failed*&lt;br&gt;::{{shutdown,&lt;br&gt;    &nbsp;{connection_closing,{server_initiated_close,541,&lt;&lt;&quot;INTERNAL_ERROR&quot;&gt;&gt;}}},&lt;br&gt;<br>
 {gen_server,call,&lt;br&gt;    &nbsp;[&lt;0.376.0&gt;,&lt;br&gt;     &nbsp;{subscribe,&lt;br&gt;         &nbsp;{&#39;basic.consume&#39;,0,&lt;&lt;&quot;amq.gen-oLyn5EMpJMlNvSMfgN9q&quot;...&gt;&gt;,&lt;&lt;&gt;&gt;,false,&lt;br&gt;             &nbsp;true,false,false,[]},&lt;br&gt;<br>
         &nbsp;&lt;0.356.0&gt;},&lt;br&gt;     &nbsp;infinity]}}&lt;br&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Thanks,&lt;br&gt;&lt;br&gt;kévin&lt;br&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;<br>

</tt>
