<tt>
&lt;div&nbsp;dir=&quot;ltr&quot;&gt;Hi,&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;I&nbsp;think&nbsp;there&nbsp;is&nbsp;a&nbsp;bug&nbsp;in&nbsp;pika&amp;#39;s&nbsp;HeartbeatChecker.&lt;/div&gt;&lt;div&gt;When&nbsp;I&nbsp;run&nbsp;these&nbsp;scripts&nbsp;I&nbsp;get:&lt;/div&gt;&lt;div&gt;&lt;div&gt;Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;  File&nbsp;&amp;quot;D:\Testing\src\recv_demo.py&amp;quot;,&nbsp;line&nbsp;35,&nbsp;in&nbsp;&amp;lt;module&amp;gt;&lt;/div&gt;<br>
&lt;div&gt;  &nbsp; connection.ioloop.start()&lt;/div&gt;&lt;div&gt;  File&nbsp;&amp;quot;C:\Python26\Lib\site-packages\pika\adapters\select_connection.py&amp;quot;,&nbsp;line&nbsp;184,&nbsp;in&nbsp;start&lt;/div&gt;&lt;div&gt;  &nbsp; self.poller.start()&lt;/div&gt;&lt;div&gt;  File&nbsp;&amp;quot;C:\Python26\Lib\site-packages\pika\log.py&amp;quot;,&nbsp;line&nbsp;107,&nbsp;in&nbsp;debug_log&lt;/div&gt;<br>
&lt;div&gt;  &nbsp; return&nbsp;method(*args,&nbsp;**kwargs)&lt;/div&gt;&lt;div&gt;  File&nbsp;&amp;quot;C:\Python26\Lib\site-packages\pika\adapters\select_connection.py&amp;quot;,&nbsp;line&nbsp;264,&nbsp;in&nbsp;start&lt;/div&gt;&lt;div&gt;  &nbsp; self.process_timeouts()&lt;/div&gt;&lt;div&gt;  File&nbsp;&amp;quot;C:\Python26\Lib\site-packages\pika\adapters\select_connection.py&amp;quot;,&nbsp;line&nbsp;250,&nbsp;in&nbsp;process_timeouts&lt;/div&gt;<br>
&lt;div&gt;  &nbsp; self._timeouts[timeout_id][&amp;#39;handler&amp;#39;]()&lt;/div&gt;&lt;div&gt;  File&nbsp;&amp;quot;C:\Python26\Lib\site-packages\pika\log.py&amp;quot;,&nbsp;line&nbsp;107,&nbsp;in&nbsp;debug_log&lt;/div&gt;&lt;div&gt;  &nbsp; return&nbsp;method(*args,&nbsp;**kwargs)&lt;/div&gt;&lt;div&gt;  File&nbsp;&amp;quot;C:\Python26\lib\site-packages\pika\heartbeat.py&amp;quot;,&nbsp;line&nbsp;115,&nbsp;in&nbsp;send_and_check&lt;/div&gt;<br>
&lt;div&gt;  &nbsp; self.connection.send_frame(Heartbeat())&lt;/div&gt;&lt;div&gt;AttributeError:&nbsp;&amp;#39;SelectConnection&amp;#39;&nbsp;object&nbsp;has&nbsp;no&nbsp;attribute&nbsp;&amp;#39;send_frame&amp;#39;&lt;/div&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;I&nbsp;don&amp;#39;t&nbsp;always&nbsp;get&nbsp;this&nbsp;error,&nbsp;but&nbsp;if&nbsp;I&nbsp;chage&nbsp;send_frame&nbsp;to&nbsp;_send_frame&nbsp;it&nbsp;seems&nbsp;to&nbsp;work...&lt;/div&gt;<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Any&nbsp;thoughts?&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Many&nbsp;Thanks,&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Yoav&nbsp;Glazner&lt;/div&gt;&lt;/div&gt;<br>

</tt>
