<tt>
Hi&nbsp;Gavin,&lt;br&gt;&lt;br&gt;I&amp;#39;ve&nbsp;grabbed&nbsp;the&nbsp;latest&nbsp;master,&nbsp;and&nbsp;when&nbsp;I&nbsp;my&nbsp;test&nbsp;app,&nbsp;I&nbsp;get:&lt;br&gt;&lt;br&gt;(&amp;quot;&amp;#39;CallbackManager&amp;#39;&nbsp;object&nbsp;has&nbsp;no&nbsp;attribute&nbsp;&amp;#39;sanitize&amp;#39;&amp;quot;,)&lt;br&gt;&lt;br&gt;Grepping&nbsp;through&nbsp;the&nbsp;code,&nbsp;I&nbsp;don&amp;#39;t&nbsp;see&nbsp;an&nbsp;implementation&nbsp;for&nbsp;Sanitize&nbsp;anywhere.&nbsp;Callstack&nbsp;looks&nbsp;like&nbsp;this:&lt;br&gt;<br>
&lt;br&gt;_on_rpc_complete&nbsp;[blocking_connection.py:230]   &nbsp;&lt;br&gt;process&nbsp;[callback.py:161]   &nbsp;&lt;br&gt;_on_data_available&nbsp;[connection.py:701]   &nbsp;&lt;br&gt;_handle_read&nbsp;[base_connection.py:315]   &nbsp;&lt;br&gt;process_data_events&nbsp;[blocking_connection.py:95]   &nbsp;&lt;br&gt;<br>
send_method&nbsp;[blocking_connection.py:254]   &nbsp;&lt;br&gt;open&nbsp;[channel.py:236]   &nbsp;&lt;br&gt;__init__&nbsp;[blocking_connection.py:274]   &nbsp;&lt;br&gt;channel&nbsp;[blocking_connection.py:129]   &nbsp;&lt;br&gt;connect&nbsp;[throughput_confirms.py:19]   &nbsp;&lt;br&gt;&amp;lt;module&amp;gt;&nbsp;[throughput_confirms.py:108]   &nbsp;&lt;br&gt;<br>
&lt;br&gt;&lt;br&gt;   &nbsp;def&nbsp;_on_rpc_complete(self,&nbsp;frame):&lt;br&gt;&amp;gt;&amp;gt;&amp;gt;&nbsp;      &nbsp;key&nbsp;=&nbsp;self.callbacks.sanitize(frame)&lt;br&gt;&lt;br&gt;Thanks,&lt;br&gt;&lt;br&gt;Matt&lt;br&gt;<br>

</tt>
