<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20can%20not%20connect%20to%20rabbitmq%20because%0A%09pika.exceptions.ProbableAuthenticationError&In-Reply-To=%3C52373100.7040709%40rabbitmq.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="030184.html">
   <LINK REL="Next"  HREF="030189.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError</H1>
    <B>Simon MacMullen</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20can%20not%20connect%20to%20rabbitmq%20because%0A%09pika.exceptions.ProbableAuthenticationError&In-Reply-To=%3C52373100.7040709%40rabbitmq.com%3E"
       TITLE="[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError">simon at rabbitmq.com
       </A><BR>
    <I>Mon Sep 16 17:25:36 BST 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="030184.html">[rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError
</A></li>
        <LI>Next message: <A HREF="030189.html">[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#30188">[ date ]</a>
              <a href="thread.html#30188">[ thread ]</a>
              <a href="subject.html#30188">[ subject ]</a>
              <a href="author.html#30188">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hmm. That looks like some problem (in the server) encoding the response 
to connection.start-ok, i.e. connection.tune. Have you customised the 
frame_max or heartbeat setting in the rabbitmq.config file? Can you post 
your config?

Cheers, Simon

On 16/09/13 16:04, &#38816;&#22823;&#21319; wrote:
&gt;<i> hi, all
</I>&gt;<i>
</I>&gt;<i> I am newer to rabbitmq.
</I>&gt;<i>
</I>&gt;<i> I install a rabbitmq, just download, setup and startup the server. then
</I>&gt;<i> I use a simple python client to connect, but the client report a error.
</I>&gt;<i>
</I>&gt;<i> =================================================
</I>&gt;<i> Here is my version config:
</I>&gt;<i> python: 2.7
</I>&gt;<i> rabbitmq:  rabbitmq-server-generic-unix-3.1.5.tar.gz
</I>&gt;<i> erlang: otp_src_R16B01
</I>&gt;<i> pika: master
</I>&gt;<i>
</I>&gt;<i> =================================================
</I>&gt;<i> Here is my python client:
</I>&gt;<i> #!/usr/bin/env python
</I>&gt;<i> import pika
</I>&gt;<i>
</I>&gt;<i> connection = pika.BlockingConnection(pika.ConnectionParameters(
</I>&gt;<i>              host='localhost'))
</I>&gt;<i> channel = connection.channel()
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> channel.queue_declare(queue='hello')
</I>&gt;<i>
</I>&gt;<i> channel.basic_publish(exchange='',
</I>&gt;<i>              routing_key='hello',
</I>&gt;<i>              body='Hello World!')
</I>&gt;<i> print &quot; [x] Sent 'Hello World!'&quot;
</I>&gt;<i> connection.close()
</I>&gt;<i>
</I>&gt;<i> =================================================
</I>&gt;<i> Here is the error info:
</I>&gt;<i> Traceback (most recent call last):
</I>&gt;<i>    File &quot;send.py&quot;, line 5, in &lt;module&gt;
</I>&gt;<i>      host='localhost'))
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;,
</I>&gt;<i> line 123, in __init__
</I>&gt;<i>      super(BlockingConnection, self).__init__(parameters, None, False)
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;,
</I>&gt;<i> line 62, in __init__
</I>&gt;<i>      on_close_callback)
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/connection.py&quot;,
</I>&gt;<i> line 593, in __init__
</I>&gt;<i>      self.connect()
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;,
</I>&gt;<i> line 223, in connect
</I>&gt;<i>      error = self._adapter_connect()
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;,
</I>&gt;<i> line 302, in _adapter_connect
</I>&gt;<i>      self.process_data_events()
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;,
</I>&gt;<i> line 233, in process_data_events
</I>&gt;<i>      if self._handle_read():
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;,
</I>&gt;<i> line 346, in _handle_read
</I>&gt;<i>      super(BlockingConnection, self)._handle_read()
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;,
</I>&gt;<i> line 323, in _handle_read
</I>&gt;<i>      return self._handle_error(error)
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;,
</I>&gt;<i> line 287, in _handle_error
</I>&gt;<i>      self._handle_disconnect()
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;,
</I>&gt;<i> line 336, in _handle_disconnect
</I>&gt;<i>      self._adapter_disconnect()
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;,
</I>&gt;<i> line 311, in _adapter_disconnect
</I>&gt;<i>      self._check_state_on_disconnect()
</I>&gt;<i>    File
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;,
</I>&gt;<i> line 141, in _check_state_on_disconnect
</I>&gt;<i>      raise exceptions.ProbableAuthenticationError
</I>&gt;<i> pika.exceptions.ProbableAuthenticationError
</I>&gt;<i>
</I>&gt;<i> =================================================
</I>&gt;<i> Here is the log info:
</I>&gt;<i> =INFO REPORT==== 16-Sep-2013::22:27:29 ===
</I>&gt;<i> accepting AMQP connection &lt;0.322.0&gt; (127.0.0.1:44572
</I>&gt;<i> &lt;<A HREF="http://127.0.0.1:44572/">http://127.0.0.1:44572/</A>&gt; -&gt; 127.0.0.1:5672 &lt;<A HREF="http://127.0.0.1:5672/">http://127.0.0.1:5672/</A>&gt;)
</I>&gt;<i>
</I>&gt;<i> =ERROR REPORT==== 16-Sep-2013::22:27:32 ===
</I>&gt;<i> closing AMQP connection &lt;0.322.0&gt; (127.0.0.1:44572
</I>&gt;<i> &lt;<A HREF="http://127.0.0.1:44572/">http://127.0.0.1:44572/</A>&gt; -&gt; 127.0.0.1:5672 &lt;<A HREF="http://127.0.0.1:5672/">http://127.0.0.1:5672/</A>&gt;):
</I>&gt;<i> {handshake_error,starting,0,
</I>&gt;<i>      {error,badarg,'connection.start_ok',
</I>&gt;<i>          [{rabbit_framing_amqp_0_9_1,encode_method_fields,1,[]},
</I>&gt;<i>           {rabbit_binary_generator,build_simple_method_frame,3,[]},
</I>&gt;<i>           {rabbit_writer,internal_send_command,4,[]},
</I>&gt;<i>           {rabbit_reader,send_on_channel0,3,[]},
</I>&gt;<i>           {rabbit_reader,auth_phase,2,[]},
</I>&gt;<i>           {rabbit_reader,handle_method0,3,[]},
</I>&gt;<i>           {rabbit_reader,handle_input,3,[]},
</I>&gt;<i>           {rabbit_reader,recvloop,2,[]}]}}
</I>&gt;<i>
</I>&gt;<i> =================================================
</I>&gt;<i> *Anyone can tell me what's the problem?*
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> _______________________________________________
</I>&gt;<i> rabbitmq-discuss mailing list
</I>&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.rabbitmq.com</A>
</I>&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss</A>
</I>&gt;<i>
</I>

-- 
Simon MacMullen
RabbitMQ, Pivotal
</PRE>













<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="030184.html">[rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError
</A></li>
	<LI>Next message: <A HREF="030189.html">[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#30188">[ date ]</a>
              <a href="thread.html#30188">[ thread ]</a>
              <a href="subject.html#30188">[ subject ]</a>
              <a href="author.html#30188">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
