<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20can%20not%20connect%20to%20rabbitmq%20because%0A%09pika.exceptions.ProbableAuthenticationError&In-Reply-To=%3CCAD9nsJtfBphBMCvyBHQtZy5A-OrWbUo2ewx26YEn%3D2mm_20kpA%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="030188.html">
   <LINK REL="Next"  HREF="030191.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError</H1>
    <B>&#38816;&#22823;&#21319;</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20can%20not%20connect%20to%20rabbitmq%20because%0A%09pika.exceptions.ProbableAuthenticationError&In-Reply-To=%3CCAD9nsJtfBphBMCvyBHQtZy5A-OrWbUo2ewx26YEn%3D2mm_20kpA%40mail.gmail.com%3E"
       TITLE="[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError">dashengju at gmail.com
       </A><BR>
    <I>Mon Sep 16 17:32:08 BST 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="030188.html">[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError
</A></li>
        <LI>Next message: <A HREF="030191.html">[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#30189">[ date ]</a>
              <a href="thread.html#30189">[ thread ]</a>
              <a href="subject.html#30189">[ subject ]</a>
              <a href="author.html#30189">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I did not set frame_max.

Here is my config:

[
    {rabbit, [
                {tcp_listeners, [5672]},
                {log_levels, [{connection, info}]}
            ]},
    {rabbitmq_mochiweb, [
                {listeners, [{mgmt, [{port, 8091}]}]}
            ]}
].

=========================================================

By the way, I change rabbitmq-server version to 2.8.7, send.py and recv.py
can send/recv message.
But I want to know why?




On Tue, Sep 17, 2013 at 12:25 AM, Simon MacMullen &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">simon at rabbitmq.com</A>&gt;wrote:

&gt;<i> Hmm. That looks like some problem (in the server) encoding the response to
</I>&gt;<i> connection.start-ok, i.e. connection.tune. Have you customised the
</I>&gt;<i> frame_max or heartbeat setting in the rabbitmq.config file? Can you post
</I>&gt;<i> your config?
</I>&gt;<i>
</I>&gt;<i> Cheers, Simon
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> On 16/09/13 16:04, &#38816;&#22823;&#21319; wrote:
</I>&gt;<i>
</I>&gt;&gt;<i> hi, all
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I am newer to rabbitmq.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I install a rabbitmq, just download, setup and startup the server. then
</I>&gt;&gt;<i> I use a simple python client to connect, but the client report a error.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> ==============================**===================
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Here is my version config:
</I>&gt;&gt;<i> python: 2.7
</I>&gt;&gt;<i> rabbitmq:  rabbitmq-server-generic-unix-**3.1.5.tar.gz
</I>&gt;&gt;<i> erlang: otp_src_R16B01
</I>&gt;&gt;<i> pika: master
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> ==============================**===================
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Here is my python client:
</I>&gt;&gt;<i> #!/usr/bin/env python
</I>&gt;&gt;<i> import pika
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> connection = pika.BlockingConnection(pika.**ConnectionParameters(
</I>&gt;&gt;<i>              host='localhost'))
</I>&gt;&gt;<i> channel = connection.channel()
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> channel.queue_declare(queue='**hello')
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> channel.basic_publish(**exchange='',
</I>&gt;&gt;<i>              routing_key='hello',
</I>&gt;&gt;<i>              body='Hello World!')
</I>&gt;&gt;<i> print &quot; [x] Sent 'Hello World!'&quot;
</I>&gt;&gt;<i> connection.close()
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> ==============================**===================
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Here is the error info:
</I>&gt;&gt;<i> Traceback (most recent call last):
</I>&gt;&gt;<i>    File &quot;send.py&quot;, line 5, in &lt;module&gt;
</I>&gt;&gt;<i>      host='localhost'))
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/**blocking_connection.py&quot;,
</I>&gt;&gt;<i> line 123, in __init__
</I>&gt;&gt;<i>      super(BlockingConnection, self).__init__(parameters, None, False)
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/base_**connection.py&quot;,
</I>&gt;&gt;<i> line 62, in __init__
</I>&gt;&gt;<i>      on_close_callback)
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/connection.py&quot;,
</I>&gt;&gt;<i> line 593, in __init__
</I>&gt;&gt;<i>      self.connect()
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/**blocking_connection.py&quot;,
</I>&gt;&gt;<i> line 223, in connect
</I>&gt;&gt;<i>      error = self._adapter_connect()
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/**blocking_connection.py&quot;,
</I>&gt;&gt;<i> line 302, in _adapter_connect
</I>&gt;&gt;<i>      self.process_data_events()
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/**blocking_connection.py&quot;,
</I>&gt;&gt;<i> line 233, in process_data_events
</I>&gt;&gt;<i>      if self._handle_read():
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/**blocking_connection.py&quot;,
</I>&gt;&gt;<i> line 346, in _handle_read
</I>&gt;&gt;<i>      super(BlockingConnection, self)._handle_read()
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/base_**connection.py&quot;,
</I>&gt;&gt;<i> line 323, in _handle_read
</I>&gt;&gt;<i>      return self._handle_error(error)
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/base_**connection.py&quot;,
</I>&gt;&gt;<i> line 287, in _handle_error
</I>&gt;&gt;<i>      self._handle_disconnect()
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/**blocking_connection.py&quot;,
</I>&gt;&gt;<i> line 336, in _handle_disconnect
</I>&gt;&gt;<i>      self._adapter_disconnect()
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/**blocking_connection.py&quot;,
</I>&gt;&gt;<i> line 311, in _adapter_disconnect
</I>&gt;&gt;<i>      self._check_state_on_**disconnect()
</I>&gt;&gt;<i>    File
</I>&gt;&gt;<i> &quot;/usr/local/lib/python2.7/**dist-packages/pika-0.9.14p0-**
</I>&gt;&gt;<i> py2.7.egg/pika/adapters/base_**connection.py&quot;,
</I>&gt;&gt;<i> line 141, in _check_state_on_disconnect
</I>&gt;&gt;<i>      raise exceptions.**ProbableAuthenticationError
</I>&gt;&gt;<i> pika.exceptions.**ProbableAuthenticationError
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> ==============================**===================
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Here is the log info:
</I>&gt;&gt;<i> =INFO REPORT==== 16-Sep-2013::22:27:29 ===
</I>&gt;&gt;<i> accepting AMQP connection &lt;0.322.0&gt; (127.0.0.1:44572
</I>&gt;&gt;<i> &lt;<A HREF="http://127.0.0.1:44572/">http://127.0.0.1:44572/</A>&gt; -&gt; 127.0.0.1:5672 &lt;<A HREF="http://127.0.0.1:5672/">http://127.0.0.1:5672/</A>&gt;)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> =ERROR REPORT==== 16-Sep-2013::22:27:32 ===
</I>&gt;&gt;<i> closing AMQP connection &lt;0.322.0&gt; (127.0.0.1:44572
</I>&gt;&gt;<i> &lt;<A HREF="http://127.0.0.1:44572/">http://127.0.0.1:44572/</A>&gt; -&gt; 127.0.0.1:5672 &lt;<A HREF="http://127.0.0.1:5672/">http://127.0.0.1:5672/</A>&gt;):
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> {handshake_error,starting,0,
</I>&gt;&gt;<i>      {error,badarg,'connection.**start_ok',
</I>&gt;&gt;<i>          [{rabbit_framing_amqp_0_9_1,**encode_method_fields,1,[]},
</I>&gt;&gt;<i>           {rabbit_binary_generator,**build_simple_method_frame,3,[]**},
</I>&gt;&gt;<i>           {rabbit_writer,internal_send_**command,4,[]},
</I>&gt;&gt;<i>           {rabbit_reader,send_on_**channel0,3,[]},
</I>&gt;&gt;<i>           {rabbit_reader,auth_phase,2,[]**},
</I>&gt;&gt;<i>           {rabbit_reader,handle_method0,**3,[]},
</I>&gt;&gt;<i>           {rabbit_reader,handle_input,3,**[]},
</I>&gt;&gt;<i>           {rabbit_reader,recvloop,2,[]}]**}}
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> ==============================**===================
</I>&gt;&gt;<i> *Anyone can tell me what's the problem?*
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> ______________________________**_________________
</I>&gt;&gt;<i> rabbitmq-discuss mailing list
</I>&gt;&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.</A>**rabbitmq.com&lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.rabbitmq.com</A>&gt;
</I>&gt;&gt;<i> <A HREF="https://lists.rabbitmq.com/**cgi-bin/mailman/listinfo/**rabbitmq-discuss&lt;https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">https://lists.rabbitmq.com/**cgi-bin/mailman/listinfo/**rabbitmq-discuss&lt;https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss</A>&gt;
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;<i> --
</I>&gt;<i> Simon MacMullen
</I>&gt;<i> RabbitMQ, Pivotal
</I>&gt;<i>
</I>


-- 
dashengju
+86 13810875910
<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">dashengju at gmail.com</A>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20130917/400ad243/attachment.htm">http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20130917/400ad243/attachment.htm</A>&gt;
</PRE>













<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="030188.html">[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError
</A></li>
	<LI>Next message: <A HREF="030191.html">[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#30189">[ date ]</a>
              <a href="thread.html#30189">[ thread ]</a>
              <a href="subject.html#30189">[ subject ]</a>
              <a href="author.html#30189">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
