<tt>
&lt;div&nbsp;dir=&quot;ltr&quot;&gt;&lt;div&gt;I&nbsp;want&nbsp;to&nbsp;execute&nbsp;a&nbsp;set&nbsp;of&nbsp;actions&nbsp;in&nbsp;parallel,&nbsp;so&nbsp;I&nbsp;am&nbsp;trying&nbsp;to&nbsp;run&nbsp;python&nbsp;multiprocessing&nbsp;to&nbsp;execute&nbsp;a&nbsp;remote&nbsp;function&nbsp;that&nbsp;I&nbsp;call&nbsp;with&nbsp;the&nbsp;help&nbsp;of&nbsp;celery.&lt;/div&gt;&lt;div&gt;RabbitMQ&nbsp;is&nbsp;the&nbsp;message&nbsp;broker.&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;My&nbsp;program&nbsp;runs&nbsp;&nbsp;ok&nbsp;if&nbsp;I&nbsp;just&nbsp;run&nbsp;one&nbsp;process.&nbsp;But&nbsp;when&nbsp;I&nbsp;run&nbsp;more&nbsp;than&nbsp;one&nbsp;process,&nbsp;I&nbsp;get&nbsp;the&nbsp;error&nbsp;below.&nbsp;As&nbsp;far&nbsp;as&nbsp;I&nbsp;got,&nbsp;the&nbsp;issue&nbsp;is&nbsp;with&nbsp;concurrent&nbsp;publishing&nbsp;on&nbsp;the&nbsp;same&nbsp;channel.&nbsp;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;RabbitMQ&nbsp;doesn't&nbsp;support&nbsp;concurrent&nbsp;call?&nbsp;I&nbsp;should&nbsp;make&nbsp;this&nbsp;call&nbsp;serializable?&lt;br&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;div&gt;&nbsp;&nbsp;File&nbsp;&quot;/usr/local/lib/python2.7/dist-packages/amqp/connection.py&quot;,&nbsp;line&nbsp;526,&nbsp;in&nbsp;_close&lt;/div&gt;&lt;div&gt;&nbsp;&nbsp;&nbsp;&nbsp;(class_id,&nbsp;method_id),&nbsp;ConnectionError)&lt;/div&gt;&lt;div&gt;UnexpectedFrame:&nbsp;Basic.publish:&nbsp;(505)&nbsp;UNEXPECTED_FRAME&nbsp;-&nbsp;expected&nbsp;content&nbsp;header&nbsp;for&nbsp;class&nbsp;60,&nbsp;got&nbsp;non&nbsp;content&nbsp;header&nbsp;frame&nbsp;instead&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;
</tt>
