<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] queue related error when declaring an	exchange
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20queue%20related%20error%20when%20declaring%20an%0A%09exchange&In-Reply-To=%3C4CA8323C.4090203%40rabbitmq.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="009269.html">
   <LINK REL="Next"  HREF="009273.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] queue related error when declaring an	exchange</H1>
    <B>Matthias Radestock</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20queue%20related%20error%20when%20declaring%20an%0A%09exchange&In-Reply-To=%3C4CA8323C.4090203%40rabbitmq.com%3E"
       TITLE="[rabbitmq-discuss] queue related error when declaring an	exchange">matthias at rabbitmq.com
       </A><BR>
    <I>Sun Oct  3 08:35:24 BST 2010</I>
    <P><UL>
        <LI>Previous message: <A HREF="009269.html">[rabbitmq-discuss] queue related error when declaring an exchange
</A></li>
        <LI>Next message: <A HREF="009273.html">[rabbitmq-discuss] queue related error when declaring an	exchange
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#9271">[ date ]</a>
              <a href="thread.html#9271">[ thread ]</a>
              <a href="subject.html#9271">[ subject ]</a>
              <a href="author.html#9271">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Ovidiu,

Ovidiu Deac wrote:
&gt;<i> I get this exception when I try to declare an exchange:
</I>&gt;<i> [...]
</I>&gt;<i> Does anybody know why it complains about QUEUE NOT FOUND when I call
</I>&gt;<i> ExchangeDeclare?
</I>
Are you perhaps setting NoWait=true in a preceding queue declaration?

When an asynchronous command causes an exception it is possible for that 
exception to be returned against the next synchronous command since the 
client API has no way of telling which of the two commands caused the 
exception.


Regards,

Matthias.
</PRE>



















<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="009269.html">[rabbitmq-discuss] queue related error when declaring an exchange
</A></li>
	<LI>Next message: <A HREF="009273.html">[rabbitmq-discuss] queue related error when declaring an	exchange
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#9271">[ date ]</a>
              <a href="thread.html#9271">[ thread ]</a>
              <a href="subject.html#9271">[ subject ]</a>
              <a href="author.html#9271">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
