<tt>
Hi&nbsp;all,&lt;br&gt;&lt;br&gt;In&nbsp;our&nbsp;organization,&nbsp;as&nbsp;part&nbsp;of&nbsp;one&nbsp;product&nbsp;we&nbsp;are&nbsp;building&nbsp;a&nbsp;multinode&nbsp;openstack&nbsp;setup.&nbsp;The&nbsp;setup&nbsp;contains&nbsp;once&nbsp;controller&nbsp;node(api,&nbsp;scheduler,&nbsp;cert&nbsp;services&nbsp;are&nbsp;installed&nbsp;in&nbsp;it)&nbsp;and&nbsp;more&nbsp;than&nbsp;one&nbsp;compute&nbsp;nodes(Compute&nbsp;and&nbsp;Network&nbsp;services&nbsp;are&nbsp;installed&nbsp;in&nbsp;it).&nbsp;In&nbsp;this&nbsp;setup,&nbsp;sometimes&nbsp;the&nbsp;rabbitmq&nbsp;service&nbsp;is&nbsp;getting&nbsp;continuously&nbsp;hanged,&nbsp;with&nbsp;the&nbsp;command&nbsp;&lt;span&nbsp;style=&quot;background-color:&nbsp;rgb(255,&nbsp;255,&nbsp;0);&quot;&gt;&lt;b&gt;rabbitmqctl&nbsp;list_queues&lt;/b&gt;&lt;/span&gt;,&nbsp;not&nbsp;all&nbsp;the&nbsp;compute&nbsp;nodes&nbsp;are&nbsp;listing.&nbsp;&lt;br&gt;&lt;br&gt;In&nbsp;the&nbsp;scheduler&nbsp;logs,&nbsp;we&nbsp;are&nbsp;continuously&nbsp;getting&nbsp;the&nbsp;following&nbsp;error.&lt;br&gt;&lt;span&nbsp;style=&quot;color:&nbsp;rgb(153,&nbsp;0,&nbsp;255);&quot;&gt;&lt;font&nbsp;size=&quot;1&quot;&gt;&lt;br&gt;&lt;span&nbsp;style=&quot;color:&nbsp;rgb(19,&nbsp;79,&nbsp;92);&quot;&gt;2013-01-18&nbsp;07:29:02&nbsp;INFO&nbsp;nova.rpc.common&nbsp;[-]&nbsp;Reconnecting&nbsp;to&nbsp;AMQP&nbsp;server&nbsp;on&nbsp;---------------&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;ERROR&nbsp;nova.rpc.common&nbsp;[-]&nbsp;AMQP&nbsp;server&nbsp;on&nbsp;--------------&nbsp;is&nbsp;unreachable:&nbsp;[Errno&nbsp;111]&nbsp;ECONNREFUSED.&nbsp;Trying&nbsp;again&nbsp;in&nbsp;3&nbsp;seconds.&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&nbsp;Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&nbsp;File&nbsp;&quot;/usr/local/lib/python2.7/dist-packages/nova-2012.1.1-py2.7.egg/nova/rpc/impl_kombu.py&quot;,&nbsp;line&nbsp;446,&nbsp;in&nbsp;reconnect&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&nbsp;self._connect()&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&nbsp;File&nbsp;&quot;/usr/local/lib/python2.7/dist-packages/nova-2012.1.1-py2.7.egg/nova/rpc/impl_kombu.py&quot;,&nbsp;line&nbsp;423,&nbsp;in&nbsp;_connect&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&nbsp;self.connection.connect()&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&nbsp;File&nbsp;&quot;/usr/lib/python2.7/dist-packages/kombu/connection.py&quot;,&nbsp;line&nbsp;95,&nbsp;in&nbsp;connect&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&nbsp;return&nbsp;self.connection&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&nbsp;File&nbsp;&quot;/usr/lib/python2.7/dist-packages/kombu/connection.py&quot;,&nbsp;line&nbsp;396,&nbsp;in&nbsp;connection&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&nbsp;self._connection&nbsp;=&nbsp;self._establish_connection()&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&nbsp;File&nbsp;&quot;/usr/lib/python2.7/dist-packages/kombu/connection.py&quot;,&nbsp;line&nbsp;364,&nbsp;in&nbsp;_establish_connection&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&nbsp;return&nbsp;self.transport.establish_connection()&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&nbsp;File&nbsp;&quot;/usr/lib/python2.7/dist-packages/kombu/transport/pyamqplib.py&quot;,&nbsp;line&nbsp;219,&nbsp;in&nbsp;establish_connection&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&nbsp;connect_timeout=conninfo.connect_timeout)&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&nbsp;File&nbsp;&quot;/usr/lib/python2.7/dist-packages/kombu/transport/pyamqplib.py&quot;,&nbsp;line&nbsp;45,&nbsp;in&nbsp;__init__&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&nbsp;super(Connection,&nbsp;self).__init__(*args,&nbsp;**kwargs)&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&nbsp;File&nbsp;&quot;/usr/lib/python2.7/dist-packages/amqplib/client_0_8/connection.py&quot;,&nbsp;line&nbsp;129,&nbsp;in&nbsp;__init__&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&nbsp;self.transport&nbsp;=&nbsp;create_transport(host,&nbsp;connect_timeout,&nbsp;ssl)&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&nbsp;File&nbsp;&quot;/usr/lib/python2.7/dist-packages/amqplib/client_0_8/transport.py&quot;,&nbsp;line&nbsp;281,&nbsp;in&nbsp;create_transport&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&nbsp;return&nbsp;TCPTransport(host,&nbsp;connect_timeout)&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&nbsp;File&nbsp;&quot;/usr/lib/python2.7/dist-packages/amqplib/client_0_8/transport.py&quot;,&nbsp;line&nbsp;85,&nbsp;in&nbsp;__init__&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&nbsp;raise&nbsp;socket.error,&nbsp;msg&lt;br&gt;2013-01-18&nbsp;07:29:02&nbsp;TRACE&nbsp;nova.rpc.common&nbsp;error:&nbsp;[Errno&nbsp;111]&nbsp;ECONNREFUSED&lt;/span&gt;&lt;/font&gt;&lt;/span&gt;&lt;br&gt;&lt;br&gt;&lt;br&gt;Can&nbsp;any&nbsp;one&nbsp;please&nbsp;suggest&nbsp;the&nbsp;solution,&nbsp;how&nbsp;can&nbsp;i&nbsp;make&nbsp;the&nbsp;rabbitmq&nbsp;server&nbsp;service&nbsp;available&nbsp;all&nbsp;the&nbsp;time.&lt;br&gt;&lt;br&gt;Thanks&nbsp;in&nbsp;advance,&lt;br&gt;D&nbsp;Anil&nbsp;Kumar.&lt;br&gt;
</tt>
