<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=%5Brabbitmq-discuss%5D%20py-amqplib%20doesn%27t%20like%20Rabbit%20user%20refusals&In-Reply-To=4987780B.3020201%40lshift.net">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="002844.html">
   <LINK REL="Next"  HREF="002850.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals</H1>
    <B>Jason J. W. Williams</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=%5Brabbitmq-discuss%5D%20py-amqplib%20doesn%27t%20like%20Rabbit%20user%20refusals&In-Reply-To=4987780B.3020201%40lshift.net"
       TITLE="[rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals">jasonjwwilliams at gmail.com
       </A><BR>
    <I>Mon Feb  2 22:54:58 GMT 2009</I>
    <P><UL>
        <LI>Previous message: <A HREF="002844.html">[rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals
</A></li>
        <LI>Next message: <A HREF="002850.html">[rabbitmq-discuss] question on exchange type
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2845">[ date ]</a>
              <a href="thread.html#2845">[ thread ]</a>
              <a href="subject.html#2845">[ subject ]</a>
              <a href="author.html#2845">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>That explains the error then. py-amqplib is calling a next_frame, but
there is no data.

-J

On Mon, Feb 2, 2009 at 3:47 PM, Matthias Radestock &lt;<A HREF="http://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">matthias at lshift.net</A>&gt; wrote:
&gt;<i> Jason,
</I>&gt;<i>
</I>&gt;<i> Jason J. W. Williams wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> It appears that py-amqplib really doesn't like it when you try to log
</I>&gt;&gt;<i> on to a vhost with a user that lacks authorization. Instead of
</I>&gt;&gt;<i> specific exception, a struct.error exception is raised with this
</I>&gt;&gt;<i> traceback:
</I>&gt;&gt;<i> [...]
</I>&gt;&gt;<i> The RabbitMQ side reports a rather sane error:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> {channel0_error,starting,
</I>&gt;&gt;<i>                {amqp,access_refused,&quot;login refused for user 'argus'&quot;,
</I>&gt;&gt;<i>                      'connection.start_ok'}}
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Is py-amqplib just not set up to cleanly handle user refusals, or is
</I>&gt;&gt;<i> this an unknown bug?
</I>&gt;<i>
</I>&gt;<i> The server does not pass any information to the client in this case. That is
</I>&gt;<i> a requirement of the spec. See section 2.2.4 of the AMQP 0-9-1 spec: &quot;prior
</I>&gt;<i> to sending or receiving Open or Open-Ok, a peer that detects an error MUST
</I>&gt;<i> close the socket without sending any further data.&quot;
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> Matthias.
</I>&gt;<i>
</I>

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="002844.html">[rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals
</A></li>
	<LI>Next message: <A HREF="002850.html">[rabbitmq-discuss] question on exchange type
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2845">[ date ]</a>
              <a href="thread.html#2845">[ thread ]</a>
              <a href="subject.html#2845">[ subject ]</a>
              <a href="author.html#2845">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
