<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=%5Brabbitmq-discuss%5D%20py-amqplib%20doesn%27t%20like%20Rabbit%20user%20refusals&In-Reply-To=3b949f090902021432s69c6b947i3e2a3a3540d3a06e%40mail.gmail.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="002842.html">
   <LINK REL="Next"  HREF="002845.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals</H1>
    <B>Matthias Radestock</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=%5Brabbitmq-discuss%5D%20py-amqplib%20doesn%27t%20like%20Rabbit%20user%20refusals&In-Reply-To=3b949f090902021432s69c6b947i3e2a3a3540d3a06e%40mail.gmail.com"
       TITLE="[rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals">matthias at lshift.net
       </A><BR>
    <I>Mon Feb  2 22:47:39 GMT 2009</I>
    <P><UL>
        <LI>Previous message: <A HREF="002842.html">[rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals
</A></li>
        <LI>Next message: <A HREF="002845.html">[rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2844">[ date ]</a>
              <a href="thread.html#2844">[ thread ]</a>
              <a href="subject.html#2844">[ subject ]</a>
              <a href="author.html#2844">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Jason,

Jason J. W. Williams wrote:
&gt;<i> It appears that py-amqplib really doesn't like it when you try to log
</I>&gt;<i> on to a vhost with a user that lacks authorization. Instead of
</I>&gt;<i> specific exception, a struct.error exception is raised with this
</I>&gt;<i> traceback:
</I>&gt;<i> [...]
</I>&gt;<i> The RabbitMQ side reports a rather sane error:
</I>&gt;<i> 
</I>&gt;<i> {channel0_error,starting,
</I>&gt;<i>                 {amqp,access_refused,&quot;login refused for user 'argus'&quot;,
</I>&gt;<i>                       'connection.start_ok'}}
</I>&gt;<i> 
</I>&gt;<i> Is py-amqplib just not set up to cleanly handle user refusals, or is
</I>&gt;<i> this an unknown bug?
</I>
The server does not pass any information to the client in this case. 
That is a requirement of the spec. See section 2.2.4 of the AMQP 0-9-1 
spec: &quot;prior to sending or receiving Open or Open-Ok, a peer that 
detects an error MUST close the socket without sending any further data.&quot;


Matthias.


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="002842.html">[rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals
</A></li>
	<LI>Next message: <A HREF="002845.html">[rabbitmq-discuss] py-amqplib doesn't like Rabbit user refusals
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2844">[ date ]</a>
              <a href="thread.html#2844">[ thread ]</a>
              <a href="subject.html#2844">[ subject ]</a>
              <a href="author.html#2844">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
